### ISSUE TITLE
LilyBukkit dumps all of its files in `~` instead of `.`

### ISSUE THREAD

**Issue by TheAwesome98-Real** [LilyBukkit/LilyBukkit-QA#45]
LilyBukkit dumps all of its files in my home folder instead of alongside the jar. I think this is because instead of `new File(…)` or `new Dir(…)` you do `this.…` which isn't a file, but a path, though I might be wrong.

**Comment by Vladg24YT** [comment]
Does this bug occur on 2.0.0.2 or the latest devbuild?

**Comment by TheAwesome98-Real** [comment]
latest devbuild 404s, and 2.0.0.2 is the version was using when this bug occured.

**Comment by Vladg24YT** [comment]
Seems like an issue with your OS's working directory environment variable. I suggest starting the server via a script that is in the same folder as the server jar, or open the folder with the jar in the terminal via the "Open in terminal" context menu option.

**Comment by TheAwesome98-Real** [comment]
i did open it by double clicking and i don't normally do that so i could try using a script like i normally do

**Comment by TheAwesome98-Real** [comment]
actually yeah it's the jvm's issue because this happened with another jar i downloaded
